acseo_sylius_geo_plugin_api_shop_product_markdown:
    path: /{slug}
    methods: [GET]
    defaults:
        _controller: ACSEO\SyliusGeoPlugin\Controller\Api\ProductMarkdownApiController
        _sylius:
            section: shop_api
    requirements:
        slug: '[^/]+'
