acseo_sylius_geo_plugin_shop_product_markdown:
    path: /{slug}.md
    methods: [GET]
    defaults:
        _controller: ACSEO\SyliusGeoPlugin\Controller\ProductMarkdownController
        _sylius:
            section: shop
    requirements:
        slug: '[^/]+'
